package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (string, error) {
	in := r.InputMapper.MapLoginInput(input)

	token, err := r.Auth.Login(ctx, in)
	if err != nil {
		return "", err
	}

	return token, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	err := r.Auth.Logout(ctx)
	if err != nil {
		return false, err
	}

	return true, nil
}

// ChangeLogin is the resolver for the changeLogin field.
func (r *mutationResolver) ChangeLogin(ctx context.Context, input model.LoginInput) (bool, error) {
	in := r.InputMapper.MapLoginInput(input)

	err := r.Auth.ChangeLogin(ctx, in)
	if err != nil {
		return false, err
	}

	return true, nil
}
