package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// SetGeneralConfig is the resolver for the setGeneralConfig field.
func (r *mutationResolver) SetGeneralConfig(ctx context.Context, config model.GeneralConfigInput) (bool, error) {
	cfg := r.InputMapper.MapGeneralConfigInput(config)

	err := r.ConfigStore.SaveGeneralConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetDiscordConfig is the resolver for the setDiscordConfig field.
func (r *mutationResolver) SetDiscordConfig(ctx context.Context, config model.DiscordConfigInput) (bool, error) {
	cfg := r.InputMapper.MapDiscordConfigInput(config)

	err := r.ConfigStore.SaveDiscordConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetPlexConfig is the resolver for the setPlexConfig field.
func (r *mutationResolver) SetPlexConfig(ctx context.Context, config model.PlexConfigInput) (bool, error) {
	cfg := r.InputMapper.MapPlexConfigInput(config)

	err := r.ConfigStore.SavePlexConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetYoutubeConfig is the resolver for the setYoutubeConfig field.
func (r *mutationResolver) SetYoutubeConfig(ctx context.Context, config model.YoutubeConfigInput) (bool, error) {
	cfg := r.InputMapper.MapYoutubeConfigInput(config)

	err := r.ConfigStore.SaveYoutubeConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetTidalConfig is the resolver for the setTidalConfig field.
func (r *mutationResolver) SetTidalConfig(ctx context.Context, config model.TidalConfigInput) (bool, error) {
	cfg := r.InputMapper.MapTidalConfigInput(config)

	err := r.ConfigStore.SaveTidalConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetGeneralConfig is the resolver for the getGeneralConfig field.
func (r *queryResolver) GetGeneralConfig(ctx context.Context) (*model.GeneralConfig, error) {
	config, err := r.ConfigStore.GetGeneralConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapGeneralConfig(config), nil
}

// GetDiscordConfig is the resolver for the getDiscordConfig field.
func (r *queryResolver) GetDiscordConfig(ctx context.Context) (*model.DiscordConfig, error) {
	config, err := r.ConfigStore.GetDiscordConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapDiscordConfig(config), nil
}

// GetPlexConfig is the resolver for the getPlexConfig field.
func (r *queryResolver) GetPlexConfig(ctx context.Context) (*model.PlexConfig, error) {
	config, err := r.ConfigStore.GetPlexConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapPlexConfig(config), nil
}

// GetYoutubeConfig is the resolver for the getYoutubeConfig field.
func (r *queryResolver) GetYoutubeConfig(ctx context.Context) (*model.YoutubeConfig, error) {
	config, err := r.ConfigStore.GetYoutubeConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapYoutubeConfig(config), nil
}

// GetTidalConfig is the resolver for the getTidalConfig field.
func (r *queryResolver) GetTidalConfig(ctx context.Context) (*model.TidalConfig, error) {
	config, err := r.ConfigStore.GetTidalConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapTidalConfig(config), nil
}
