package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// SetDiscordConfig is the resolver for the setDiscordConfig field.
func (r *mutationResolver) SetDiscordConfig(ctx context.Context, config model.DiscordConfigInput) (bool, error) {
	cfg := r.InputMapper.MapDiscordConfigInput(config)

	err := r.ConfigStore.SaveDiscordConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetPlexConfig is the resolver for the setPlexConfig field.
func (r *mutationResolver) SetPlexConfig(ctx context.Context, config model.PlexConfigInput) (bool, error) {
	cfg := r.InputMapper.MapPlexConfigInput(config)

	err := r.ConfigStore.SavePlexConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetDiscordConfig is the resolver for the getDiscordConfig field.
func (r *queryResolver) GetDiscordConfig(ctx context.Context) (*model.DiscordConfig, error) {
	config, err := r.ConfigStore.GetDiscordConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapDiscordConfig(config), nil
}

// GetPlexConfig is the resolver for the getPlexConfig field.
func (r *queryResolver) GetPlexConfig(ctx context.Context) (*model.PlexConfig, error) {
	config, err := r.ConfigStore.GetPlexConfig(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapPlexConfig(config), nil
}
