package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// SetDiscordConfig is the resolver for the setDiscordConfig field.
func (r *mutationResolver) SetDiscordConfig(ctx context.Context, config model.DiscordConfig) (bool, error) {
	cfg := r.InputMapper.MapDiscordConfig(config)

	err := r.ConfigStore.SaveDiscordConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SetPlexConfig is the resolver for the setPlexConfig field.
func (r *mutationResolver) SetPlexConfig(ctx context.Context, config model.PlexConfig) (bool, error) {
	cfg := r.InputMapper.MapPlexConfig(config)

	err := r.ConfigStore.SavePlexConfig(ctx, cfg)
	if err != nil {
		return false, err
	}

	return true, nil
}
