package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// RefreshPlexTracks is the resolver for the refreshPlexTracks field.
func (r *mutationResolver) RefreshPlexTracks(ctx context.Context) (bool, error) {
	err := r.Plex.RefreshTracks(ctx)
	if err != nil {
		return false, err
	}

	return true, nil
}

// RefreshPlexLibrary is the resolver for the refreshPlexLibrary field.
func (r *mutationResolver) RefreshPlexLibrary(ctx context.Context) (bool, error) {
	err := r.Plex.RefreshLibrary(ctx)
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeletePlexTrack is the resolver for the deletePlexTrack field.
func (r *mutationResolver) DeletePlexTrack(ctx context.Context, id int64) (bool, error) {
	err := r.Plex.DeleteTrack(ctx, id)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetPlexTracks is the resolver for the getPlexTracks field.
func (r *queryResolver) GetPlexTracks(ctx context.Context) ([]*model.PlexTrack, error) {
	tracks, err := r.Plex.GetTracks(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapPlexTracks(tracks), nil
}
