package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/domain"
	"github.com/CZnavody19/music-manager/src/graph/model"
)

// EnableYoutube is the resolver for the enableYoutube field.
func (r *mutationResolver) EnableYoutube(ctx context.Context, enable bool) (bool, error) {
	var err error
	if enable {
		err = r.YouTube.Enable(ctx)
	} else {
		err = r.YouTube.Disable(ctx)
	}

	if err != nil {
		return false, err
	}

	return true, nil
}

// EnableDiscord is the resolver for the enableDiscord field.
func (r *mutationResolver) EnableDiscord(ctx context.Context, enable bool) (bool, error) {
	var err error
	if enable {
		err = r.Discord.Enable(ctx)
	} else {
		err = r.Discord.Disable(ctx)
	}

	if err != nil {
		return false, err
	}

	return true, nil
}

// EnablePlex is the resolver for the enablePlex field.
func (r *mutationResolver) EnablePlex(ctx context.Context, enable bool) (bool, error) {
	var err error
	if enable {
		err = r.Plex.Enable(ctx)
	} else {
		err = r.Plex.Disable(ctx)
	}

	if err != nil {
		return false, err
	}

	return true, nil
}

// EnableTidal is the resolver for the enableTidal field.
func (r *mutationResolver) EnableTidal(ctx context.Context, enable bool) (bool, error) {
	var err error
	if enable {
		err = r.Tidal.Enable(ctx)
	} else {
		err = r.Tidal.Disable(ctx)
	}

	if err != nil {
		return false, err
	}

	return true, nil
}

// SendTestDiscordMessage is the resolver for the sendTestDiscordMessage field.
func (r *mutationResolver) SendTestDiscordMessage(ctx context.Context) (bool, error) {
	desc := "Description"
	col := 65497 // Decimal value from here: https://www.spycolor.com/

	err := r.Discord.SendMessage(ctx, &domain.DiscordMessage{
		Title:       "Test Message",
		Description: &desc,
		Color:       &col,
		Fields: []domain.DiscordMessageField{
			{
				Name:   "Field 1",
				Value:  "This is a test field",
				Inline: false,
			},
			{
				Name:   "Field 2",
				Value:  "This is another test field",
				Inline: true,
			},
		},
	})

	if err != nil {
		return false, err
	}

	return true, nil
}

// GetServiceStatus is the resolver for the getServiceStatus field.
func (r *queryResolver) GetServiceStatus(ctx context.Context) (*model.ServiceStatus, error) {
	return &model.ServiceStatus{
		Youtube: r.YouTube.IsEnabled(),
		Discord: r.Discord.IsEnabled(),
		Plex:    r.Plex.IsEnabled(),
		Tidal:   r.Tidal.IsEnabled(),
	}, nil
}
