package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
	"github.com/google/uuid"
)

// DeleteTrack is the resolver for the deleteTrack field.
func (r *mutationResolver) DeleteTrack(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.MusicBrainz.DeleteTrack(ctx, id)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetTracks is the resolver for the getTracks field.
func (r *queryResolver) GetTracks(ctx context.Context) ([]*model.Track, error) {
	tracks, err := r.MusicBrainz.GetTracks(ctx, false)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapTracks(tracks), nil
}
