package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
	"github.com/google/uuid"
)

// Tasks is the resolver for the tasks field.
func (r *subscriptionResolver) Tasks(ctx context.Context) (<-chan *model.Task, error) {
	id := uuid.New()

	channel := r.Websockets.AddSubscriber(id)

	go func() {
		<-ctx.Done()
		r.Websockets.RemoveSubscriber(id)
	}()

	return channel, nil
}
