package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CZnavody19/music-manager/src/graph/model"
)

// GetVideosInPlaylist is the resolver for the getVideosInPlaylist field.
func (r *queryResolver) GetVideosInPlaylist(ctx context.Context) ([]*model.YouTubeVideo, error) {
	videos, err := r.YouTube.GetVideos(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapYoutubeVideos(videos), nil
}
