package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/CZnavody19/music-manager/src/graph/model"
	"github.com/google/uuid"
)

// RefreshPlaylist is the resolver for the refreshPlaylist field.
func (r *mutationResolver) RefreshPlaylist(ctx context.Context) (bool, error) {
	err := r.YouTube.RefreshPlaylist(ctx)
	if err != nil {
		return false, err
	}

	return true, nil
}

// MatchVideo is the resolver for the matchVideo field.
func (r *mutationResolver) MatchVideo(ctx context.Context, videoID string, trackID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: MatchVideo - matchVideo"))
}

// GetVideosInPlaylist is the resolver for the getVideosInPlaylist field.
func (r *queryResolver) GetVideosInPlaylist(ctx context.Context) ([]*model.YouTubeVideo, error) {
	videos, err := r.YouTube.GetVideos(ctx)
	if err != nil {
		return nil, err
	}

	return r.Mapper.MapYoutubeVideos(videos), nil
}
