// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DiscordConfig struct {
	WebhookURL string `json:"webhookURL"`
}

type Mutation struct {
}

type Query struct {
}

type ServiceStatus struct {
	Youtube bool `json:"youtube"`
	Discord bool `json:"discord"`
}
