// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type DiscordConfig struct {
	WebhookURL string `json:"webhookURL"`
}

type DiscordConfigInput struct {
	WebhookURL string `json:"webhookURL"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PlexConfig struct {
	Protocol  string `json:"protocol"`
	Host      string `json:"host"`
	Port      int64  `json:"port"`
	Token     string `json:"token"`
	LibraryID int64  `json:"libraryID"`
}

type PlexConfigInput struct {
	Protocol  string `json:"protocol"`
	Host      string `json:"host"`
	Port      int64  `json:"port"`
	Token     string `json:"token"`
	LibraryID int64  `json:"libraryID"`
}

type Query struct {
}

type ServiceStatus struct {
	Youtube bool `json:"youtube"`
	Discord bool `json:"discord"`
	Plex    bool `json:"plex"`
}

type Subscription struct {
}

type Task struct {
	Title     string    `json:"title"`
	StartedAt time.Time `json:"startedAt"`
	Ended     bool      `json:"ended"`
}

type Track struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	Artist        string    `json:"artist"`
	Length        int64     `json:"length"`
	Isrcs         []string  `json:"isrcs"`
	LinkedYoutube bool      `json:"linkedYoutube"`
	LinkedPlex    bool      `json:"linkedPlex"`
}

type YouTubeVideo struct {
	ID           string `json:"id"`
	Title        string `json:"title"`
	ChannelTitle string `json:"channelTitle"`
	ThumbnailURL string `json:"thumbnailUrl"`
	Duration     int64  `json:"duration"`
	Position     int64  `json:"position"`
	Linked       bool   `json:"linked"`
}

type YoutubeConfig struct {
	PlaylistID string `json:"playlistID"`
}

type YoutubeConfigInput struct {
	PlaylistID string `json:"playlistID"`
}
